# .github/workflows/go.yaml
name: Go

on:
  schedule:
    - cron: '0 * * 1 *'

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: |
        go build -v ./...
        pwd
        ls

    - name: Test
      run: go test -v ./...

    - name: Write time to file
      run: |
        pwd
        go version
        go run main.go

    - name: Commit files
      run: |
         git config --local user.email "mingpepemath@gmail.com"
         git config --local user.name "mingpepe"
         git add .
         git commit -m "update time file"

    - name: Push changes
      uses:  ad-m/github-push-action@master
      with:
         github_token: ${{ secrets.GIT_TOKEN }}
         branch: master
